name: SKY UX CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
      - name: Build and test
        run: |
          set -x
          npm ci
          npm run build
          npm run test:ci
