name: Release Please
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: 'node'
          default-branch: '${{ github.ref_name }}'
          package-name: '@blackbaud/angular-tree-component'
          pull-request-title-pattern: 'chore: release ${version}'
          labels: 'autorelease ${{ github.ref_name }}: pending'
          release-labels: 'autorelease ${{ github.ref_name }}: tagged'
          release-as: '1.0.0-alpha.0'
          prerelease: true
          draft-pull-request: true
          include-v-in-tag: false
          token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
      - uses: actions/checkout@v3
        with:
          token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      # Workaround to avoid "Post Run actions/setup-node" failures.
      # See: https://github.com/actions/setup-node/issues/317
      - name: Ensure cache directory exists
        if: ${{ !steps.release.outputs.release_created }}
        run: mkdir -p /home/runner/.npm
        continue-on-error: true
      - name: npm install
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci
      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: npx -p @angular/cli@14 ng build angular-tree-component
      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        run: |
          node ./scripts/prepare-package.mjs
          cd dist/angular-tree-component
          npm publish --tag=next --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}